config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {registrations: 'registrations', sesions: 'sessions'}
  match 'remote_sign_in', to: 'remote_content#remote_sign_in', via: [:get]
  match 'remote_profile', to: 'remote_content#remote_pofile', via: [:get]
  resources :things

  get 'home/index'

  root 'home#index'

end

app/models/thing.rb
class Thing < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

 def create
 build_resource(sign_up_params)

 if resource.save
 respond_to do |format|
 format.html {
 yield resource if block_given?
 if resource.active_for_authentication?
 set_flash_message :notice, :signed_up if is_flashing_format?
 sign_up(resource_name, resource)
 respond_with resource, :location => after_sign_up_path_for(resource)
 else
 set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
 expire_data_after_sign_in!
 respond_with resource, :location => after_inactive_sign_up_path_for(resource)
 end
 }
 format.js {
 flash[:notice] = "Created account, signed in."
 render :template => "remote_content/devise_success_sign_up.js.erb"
 flash.discard
 sign_up(resource_name, resource)
 }
 end
 else
 respond_to do |format|
 format.html {
 clean_up_passwords resource
 respond_with resource
 }
 format.js {
 flash[:alert] = @user.errors.full_messages.to_sentence
 render :template => "remote_content/devise_errors.js.erb"
 flash.discard
 }
 end
 end
 end
end

app/controllers/remote_content_controller.rb
class RemoteContentController < ApplicationController
end

app/controllers/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
protect_from_forgery with: :null_session

def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message(:notice, :signed_in) if is_flashing_format?
    sign_in(resource_name, resource)
    yield resource if block_given?
    respond_with resource, location: after_sign_in_path_for(resource)
    redirect_to home_path
end
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  before_action :set_thing, only: [:show, :edit, :update, :destroy]

  # GET /things
  # GET /things.json
  def index
    @things = Thing.all
  end

  # GET /things/1
  # GET /things/1.json
  def show
  end

  # GET /things/new
  def new
    @thing = Thing.new
  end

  # GET /things/1/edit
  def edit
  end

  # POST /things
  # POST /things.json
  def create
    @thing = Thing.new
  # scaffold recommends Thing.new(thing_params)

    respond_to do |format|
      if @thing.save
        format.html { redirect_to @thing, notice: 'Thing was successfully created.' }
        format.json { render :show, status: :created, location: @thing }
      else
        format.html { render :new }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /things/1
  # PATCH/PUT /things/1.json
  def update
    respond_to do |format|
      if @thing.update(thing_params)
        format.html { redirect_to @thing, notice: 'Thing was successfully updated.' }
        format.json { render :show, status: :ok, location: @thing }
      else
        format.html { render :edit }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /things/1
  # DELETE /things/1.json
  def destroy
    @thing.destroy
    respond_to do |format|
      format.html { redirect_to things_url, notice: 'Thing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thing
      @thing = Thing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thing_params
      params[:thing]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_normal
   render "flashes"
  end
  def twitterized_type(type)
    case type
    when :errors
    "alert-error"
    when :alert
    "alert-warning"
    when :error
    "alert-error"
    when :notice
    "alert-success"
    else
    "alert-info"
    end
  end
  def resource_name
   :user
  end

  def resource
   @resource ||= User.new
  end

  def devise_mapping
   @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/remote_content_helper.rb
module RemoteContentHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/home/index.html.haml
%div{"ng-app" => "riff"}
  .view-container
    .view-frame.animate-view{"ng-view" => ""}

app/views/layouts/_sidebar.html.haml
- if current_user
  = link_to destroy_user_session_path, "data-method" => :delete do
    %li Sign Out
  = link_to remote_profile_path, {rel: current_user, :remote => true} do
    %li My Profile
- else
  = link_to remote_sign_in_path, {rel: 'sign_up_modal', :remote => true} do
    %li Sign Up
  = link_to remote_sign_in_path, {rel: 'sign_in_modal', :remote => true} do
    %li Sign In

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app='riff'>
<head>
  <title>riff</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <div class="login-modal"></div>
  <input id="sidebartoggler" type="checkbox">
    <div class="page-wrapper">
      <label class="toggle" for="sidebartoggler"><img src="/assets/riff_logo.png" height="45" width= "45"></label>
      <div class="page-content">
        <%= yield %>
      </div>
      <div class="sidebar">
        <li>Home</li>
        <%=render 'layouts/sidebar'%>
      </div>
    </div>
  </input>

</body>
</html>

app/views/remote_content/_remote_profile.html.haml
#profile_modal.modal
 .container1
  .modal-dialog
  .modal-content
   %h4#SignInModal.title My Profile
   %img {src="/assets/riff_logo.png" height="45" width= "45"}
   .modal-header
    .footer
     .form-actions
      %button Update Status

app/views/remote_content/_remote_sign_in.html.haml
#sign_in_modal.modal
 .container1
  .modal-dialog
  .modal-content
   %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"}
   %h4#SignInModal.title Sign into acount
   %p Fill in the following to login
   .modal-header
   = simple_form_for(resource, :as => resource_name, :url => session_path(resource_name), :remote => true, :format => :js, :html => {:class => "form-signin"}) do |f|
    .modal-body
     = text_field_tag 'user[email]', nil, :size=> 37.5
     %br
     = password_field_tag 'user[password]', nil, :size=> 37.5
     %br
     = check_box_tag 'user[remember_me]'
     = label_tag 'user[remember_me]', 'Remember me'
     %br
    .footer
     .form-actions
      %button Sign in
      %br
      = link_to "Forgot your password?", new_password_path(:user)

app/views/remote_content/_remote_sign_up.html.haml
#sign_up_modal.modal
 .container1
  .modal-dialog
  .modal-content
   %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"}
   %h4#SignInModal.title Create an account
   %p Add your details to create an account
   .modal-header
   = simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name), :remote => true, :format => :js, :html => {:class => "form-signin"}) do |f|
    .modal-body
     = f.input :email, :autofocus => true, :label => false, :placeholder => "Email", input_html: {size: 37.5}
     = f.input :password, :label => false, :placeholder => "Password", input_html: {size: 37.5}
     = f.input :password_confirmation, :label => false, :placeholder => "Confirm password", input_html: {size: 37.5}
     = link_to remote_sign_in_path, {rel: 'sign_in_modal', :remote => true} do      
      %li Already have an acount?
     = link_to new_user_password_path do
      Forgot your password?
    .footer
     .form-actions
      %a{ :href => "#", "data-dismiss" => "modal" } Cancel
      = f.button :submit, "Create account"

app/views/remote_content/remote_profile.js.erb
$('.profile').on('click', function(e) {
  console.log('profile')
  $(".profile-modal").html("<%= escape_javascript(render "remote_profile", :formats => [:html]) %>");
  $("#" + current_user).modal();
});

app/views/remote_content/remote_sign_in.js.erb
$('.sidebar').on('click', 'a', function(e) {
  e.preventDefault();
  var modalId = $(this).attr('rel');
  var tmpl;
  if(modalId === "sign_in_modal") {
    $(".login-modal").html("<%= escape_javascript(render "remote_sign_in", :formats => [:html]) %>");
  } else {
    $(".login-modal").html("<%= escape_javascript(render "remote_sign_up", :formats => [:html]) %>");
  }
  $("#" + modalId).modal();
});

app/views/things/_form.html.haml
= form_for @thing do |f|
  - if @thing.errors.any?
    #error_explanation
      %h2= "#{pluralize(@thing.errors.count, "error")} prohibited this thing from being saved:"
      %ul
        - @thing.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/things/edit.html.haml
%h1 Editing thing

= render 'form'

= link_to 'Show', @thing
\|
= link_to 'Back', things_path

app/views/things/index.html.haml
%h1 Listing things

%table
  %thead
    %tr
      %th
      %th
      %th
      
  %tbody
    - @things.each do |thing|
      %tr
        %td= link_to 'Show', thing
        %td= link_to 'Edit', edit_thing_path(thing)
        %td= link_to 'Destroy', thing, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Thing', new_thing_path

app/views/things/new.html.haml
%h1 New thing

= render 'form'

= link_to 'Back', things_path

app/views/things/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_thing_path(@thing)
\|
= link_to 'Back', things_path